### ISSUE TITLE
`eton edit` bug

### ISSUE THREAD

**Issue by DanielRivasMD** [siadat/eton#5]
Hi. I downloaded and tried your tool, and really like it. But I keep getting this error whenever I type command edit:

```
panic: bad file descriptor

goroutine 1 [running]:
main.check(...)
        /Users/drivas/.go/pkg/mod/github.com/siadat/eton@v0.0.0-20171201181454-fd531c251bc1/commands.go:408
main.attrStruct.edit(0x1, 0x1, 0x0, 0x0, 0xc0001d4ec8, 0x4, 0x1, 0x0, 0x0, 0x0, ...)
        /Users/drivas/.go/pkg/mod/github.com/siadat/eton@v0.0.0-20171201181454-fd531c251bc1/attr.go:444 +0x529
main.cmdEdit(0xc00011f2b0, 0x0, 0x0, 0x0, 0xc0001d4cd0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /Users/drivas/.go/pkg/mod/github.com/siadat/eton@v0.0.0-20171201181454-fd531c251bc1/commands.go:281 +0xf2
main.main()
        /Users/drivas/.go/pkg/mod/github.com/siadat/eton@v0.0.0-20171201181454-fd531c251bc1/main.go:131 +0xc25
``` 

I tried `eton edit`, `eton edit $ID_NUMBER`, aliasing and `eton edit $ALIAS`. I keep getting the same message.

Any help? Much appreciated. Cheers

**Comment by siadat** [comment]
Hi @DanielRivasMD. Thanks for trying eton and opening this issue!

It's been a while since I have worked on eton. My first impression is that it is probably a dependency issue. It needs to be converted into a Go module so that we could specify the version of the dependencies.

**Comment by siadat** [comment]
I pushed a few commits just now, please pull or get the code again and let me know if your problem is solved.

**Comment by DanielRivasMD** [comment]
Hi. Thanks a lot for the effort. I pulled and compiled it. It works flawlessly now. Awesome. Cheers
